FROM alpine:3.16
LABEL maintainer="nyinyisoepaing1997@gmail.com"
ENV COMPOSER_ALLOW_SUPERUSER=1
# Setup document root
WORKDIR /var/www/html

RUN apk add --no-cache \
  curl \
  nginx \
  supervisor \
  php81 \
  php81-ctype \
  php81-curl \
  php81-dom \
  php81-fileinfo \
  php81-fpm \
  php81-gd \
  php81-intl \
  php81-mbstring \
  php81-mysqli \
  php81-opcache \
  php81-openssl \
  php81-pdo \
  php81-pdo_mysql \
  php81-pdo_pgsql \
  php81-phar \
  php81-session \
  php81-simplexml \
  php81-sodium \
  php81-tokenizer \
  php81-xml \
  php81-xmlreader \
  php81-xmlwriter

# Create symlink so programs depending on `php` still function
RUN ln -s /usr/bin/php81 /usr/bin/php

# Configure nginx
COPY docker-config/nginx.conf /etc/nginx/nginx.conf

# Configure PHP-FPM
COPY docker-config/fpm-pool.conf /etc/php81/php-fpm.d/www.conf
COPY docker-config/php.ini /etc/php81/conf.d/custom.ini

# Configure supervisord
COPY docker-config/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Install composer 
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer
# # Switch to use root user from here on
USER root

# set www-data group (82 is the standard uid/gid for www-data in Alpine)
RUN set -x ; \
	addgroup -g 82 -S www-data ; \
	adduser -u 82 -D -S -G www-data www-data && exit 0 ; exit 1


# Expose the port nginx is reachable on
EXPOSE 80

# Let supervisord start nginx & php-fpm
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
