version: '3.5'
services:
  php8.1:
    build: .
    container_name: laravel-app
    volumes:
      - "./laravel:/var/www/html"
    ports:
      - "80:80"

  database:
    # platform: linux/amd64
    # image: arm64v8/mysql:8
    image: mysql:8
    container_name: mysql
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo 

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8888:80
    links:
      - database
    environment:
      PMA_HOST: database 
      PMA_PORT: 3306
      # PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 3000M

volumes:
  db-data: {}
    


